export type RootStackParamList = {
  Splash: undefined;
  Bienvenida: undefined;
  Login: undefined;
  ValidandoLogin: undefined;
  Dashboard: undefined;
  ExplorarInvitado: undefined;
  ComoPageMiCredito: undefined;
  SolicitarCreditoTienda: undefined;
  RecuperarCuenta: undefined;
  VerificacionCorreoRecuperacion: undefined;
  IngresarOtpRecuperacion: undefined;
  NuevaClave: undefined;
  ExitoRecuperacion: undefined;
  IngresoIdentificacion: undefined;
  ConfirmacionDatos: undefined;
  VerificacionCorreo: undefined;
  IngresarOtp: undefined;
  CrearClave: undefined;
  Exito: undefined;
};
